const toolkitTiersActions = {
    FETCH_TOOLKITTIERS_REQUEST: 'FETCH_TOOLKITTIERS_REQUEST',
    FETCH_TOOLKITTIERS_SUCCESS: 'FETCH_TOOLKITTIERS_SUCCESS',
    FETCH_TOOLKITTIERS_ERROR: 'FETCH_TOOLKITTIERS_ERROR',
    fetchToolkitTiers: payload => ({
        type: toolkitTiersActions.FETCH_TOOLKITTIERS_REQUEST,
    }),
    DELETE_TOOLKITTIER_REQUEST: 'DELETE_TOOLKITTIER_REQUEST',
    DELETE_TOOLKITTIER_SUCCESS: 'DELETE_TOOLKITTIER_SUCCESS',
    DELETE_TOOLKITTIER_ERROR: 'DELETE_TOOLKITTIER_ERROR',
    deleteToolkitTier: payload => ({
        type: toolkitTiersActions.DELETE_TOOLKITTIER_REQUEST,
        payload
    }),
    INSERT_TOOLKITTIER_REQUEST: 'INSERT_TOOLKITTIER_REQUEST',
    INSERT_TOOLKITTIER_SUCCESS: 'INSERT_TOOLKITTIER_SUCCESS',
    INSERT_TOOLKITTIER_ERROR: 'INSERT_TOOLKITTIER_ERROR',
    insertToolkitTier: payload => ({
        type: toolkitTiersActions.INSERT_TOOLKITTIER_REQUEST,
        payload
    }),
}
export default toolkitTiersActions;