apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      run: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        run: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: git.perceptyx.com:4567/external/smartsheets_frontend/smartsheets_frontend:${BRANCH}
          imagePullPolicy: Always
          env:
            - name: APP_VERSION
              value: ${APP_VERSION}
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: ${APPLICATION_NAME}-secrets
                  key: node_env
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: ${APPLICATION_NAME}-secrets
                  key: api_url
            - name: SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: ${APPLICATION_NAME}-secrets
                  key: server_url
          ports:
          - name: ${APPLICATION_NAME}
            containerPort: 3000
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 700Mi
              cpu: 400m
      imagePullSecrets:
        - name: gitlabregistrypullsecret
