const naicsCodesActions = {
    FETCH_NAICSCODES_REQUEST: 'FETCH_NAICSCODES_REQUEST',
    FETCH_NAICSCODES_SUCCESS: 'FETCH_NAICSCODES_SUCCESS',
    FETCH_NAICSCODES_ERROR: 'FETCH_NAICSCODES_ERROR',
    fetchNaicsCodes: payload => ({
        type: naicsCodesActions.FETCH_NAICSCODES_REQUEST,
    }),
    DELETE_NAICSCODES_REQUEST: 'DELETE_NAICSCODES_REQUEST',
    DELETE_NAICSCODES_SUCCESS: 'DELETE_NAICSCODES_SUCCESS',
    DELETE_NAICSCODES_ERROR: 'DELETE_NAICSCODES_ERROR',
    deleteNaicsCodes: payload => ({
        type: naicsCodesActions.DELETE_NAICSCODES_REQUEST,
        payload
    }),
    INSERT_NAICSCODES_REQUEST: 'INSERT_NAICSCODES_REQUEST',
    INSERT_NAICSCODES_SUCCESS: 'INSERT_NAICSCODES_SUCCESS',
    INSERT_NAICSCODES_ERROR: 'INSERT_NAICSCODES_ERROR',
    insertNaicsCodes: payload => ({
        type: naicsCodesActions.INSERT_NAICSCODES_REQUEST,
        payload
    }),
    GET_NAICSCODES_REQUEST: 'GET_NAICSCODES_REQUEST',
    GET_NAICSCODES_SUCCESS: 'GET_NAICSCODES_SUCCESS',
    GET_NAICSCODES_ERROR: 'GET_NAICSCODES_ERROR',
    getNaicsCodes: payload => ({
        type: naicsCodesActions.GET_NAICSCODES_REQUEST,
        payload
    }),
    UPDATE_NAICSCODES_REQUEST: 'UPDATE_NAICSCODES_REQUEST',
    UPDATE_NAICSCODES_SUCCESS: 'UPDATE_NAICSCODES_SUCCESS',
    UPDATE_NAICSCODES_ERROR: 'UPDATE_NAICSCODES_ERROR',
    updateNaicsCodes: payload => ({
        type: naicsCodesActions.UPDATE_NAICSCODES_REQUEST,
        payload
    }),
}
export default naicsCodesActions;