const howFoundPyxActions = {
    FETCH_HOWFOUNDPYX_REQUEST: 'FETCH_HOWFOUNDPYX_REQUEST',
    FETCH_HOWFOUNDPYX_SUCCESS: 'FETCH_HOWFOUNDPYX_SUCCESS',
    FETCH_HOWFOUNDPYX_ERROR: 'FETCH_HOWFOUNDPYX_ERROR',
    fetchHowFoundPyx: payload => ({
        type: howFoundPyxActions.FETCH_HOWFOUNDPYX_REQUEST,
    }),
    DELETE_HOWFOUNDPYX_REQUEST: 'DELETE_HOWFOUNDPYX_REQUEST',
    DELETE_HOWFOUNDPYX_SUCCESS: 'DELETE_HOWFOUNDPYX_SUCCESS',
    DELETE_HOWFOUNDPYX_ERROR: 'DELETE_HOWFOUNDPYX_ERROR',
    deleteHowFoundPyx: payload => ({
        type: howFoundPyxActions.DELETE_HOWFOUNDPYX_REQUEST,
        payload
    }),
    INSERT_HOWFOUNDPYX_REQUEST: 'INSERT_HOWFOUNDPYX_REQUEST',
    INSERT_HOWFOUNDPYX_SUCCESS: 'INSERT_HOWFOUNDPYX_SUCCESS',
    INSERT_HOWFOUNDPYX_ERROR: 'INSERT_HOWFOUNDPYX_ERROR',
    insertHowFoundPyx: payload => ({
        type: howFoundPyxActions.INSERT_HOWFOUNDPYX_REQUEST,
        payload
    }),
    GET_HOWFOUNDPYX_REQUEST: 'GET_HOWFOUNDPYX_REQUEST',
    GET_HOWFOUNDPYX_SUCCESS: 'GET_HOWFOUNDPYX_SUCCESS',
    GET_HOWFOUNDPYX_ERROR: 'GET_HOWFOUNDPYX_ERROR',
    getHowFoundPyx: payload => ({
        type: howFoundPyxActions.GET_HOWFOUNDPYX_REQUEST,
        payload
    }),
    UPDATE_HOWFOUNDPYX_REQUEST: 'UPDATE_HOWFOUNDPYX_REQUEST',
    UPDATE_HOWFOUNDPYX_SUCCESS: 'UPDATE_HOWFOUNDPYX_SUCCESS',
    UPDATE_HOWFOUNDPYX_ERROR: 'UPDATE_HOWFOUNDPYX_ERROR',
    updateHowFoundPyx: payload => ({
        type: howFoundPyxActions.UPDATE_HOWFOUNDPYX_REQUEST,
        payload
    }),
}
export default howFoundPyxActions;